default:
  http_metas:
    content-type: text/html
    imagetoolbar: 'false'

  metas:
    author:                     Southern Media
    robots:                     noodp
    MSSmartTagsPreventParsing:  'true'


#  stylesheets:    [style.css]

#  javascripts:    [combined.js]

  has_layout:     on
  layout:         layout