# default values
all:
  domain:
    name:   Recording Questions
  gravatar:
    default_size:   90
    default_rating: G
    default_image:  gravatar_default.png
    cache_dir_name: g_cache
    cache_expiration: 3 days
  question_description:
    lenth: 160
  recent_tag:
    count: 9 # Count of display recent tag on Recent Tags Widget
  sf_phpopenid_plugin:
    lib_path: '%SF_ROOT_DIR%/lib/php-openid'

  experience:
    upvote:             10
    downvote:           -2
    downvote_given:     -1
    accepted_an_answer: 2
    answer_accepted:    15
    flagged_offender:   -100

  rss_conf:
    per_page: 30
    title: "Recording question list"
    author_email: "andreyd@forma.kharkov.ua"
    author_name: "Recording question"

  statistics_page:
    answer_length: 130

  .array:
    sphinx_related_question:
      port: 3316
      limit: 1000
      offset: 1
    observer:
        'question.save':
            - fpQuestionSpamControlHandler
        'question.details':
            - fpQuestionSpamControlHandler
        'answer.save':
            - fpAnswerSpamControlHandler
        'answer.details':
            - fpAnswerSpamControlHandler
        'comment.details':
            - fpCommentSpamControlHandler
        'comment.save':
            - fpCommentSpamControlHandler
        'votes.save':
            - fpVotesSpamControlHandler
        'offensive.save':
            - fpOffensiveSpamControlHandler
        'votes.check':
            - fpVotesSpamControlHandler
        'expereinceQuestion.beforeSave':
            - fpExperienceQuestionControlHandler
        'expereinceVote.beforeSave':
            - fpExperienceVoteControlHandler
        'expereinceVote.afterSave':
            - fpExperienceVoteControlHandler
        'expereinceBestAnswer.afterSave':
            - fpExperienceBestAnswerControlHandler
        'expereinceUnsetBestAnswer.afterSave':
            - fpExpAnswerControlHandler

    question_spam:
        period: 100000 # in seconds
        limit:  100000
    answer_spam:
        period: 100000 # in seconds
        limit:  100000
    comment_spam:
        period: 100000 # in seconds
        limit:  100000
    votes_spam:
        period: 100000 # One day from 00:00 to 23:59 in seconds
        limit:  100000    # Votes count per day
    offensive_spam:
        period: 86400
        limit:  5

  experience_needed:
    upvote: 15
    downvote: 100
    add_comment: 50
  experience_add:
    vote: 10
    best_answer: 15
    select_best_answer: 2
    remove_downvote: 2
    remove_you_downvote: 1
  experience_sub:
    vote: 2
    you_downvote: 1
    offensive: 100
    remove_upvote: 10
    unset_best_answer: 2
    unset_user_best_answer: 15

  sfPropelActAsTaggableBehaviorPlugin:
    limit:   20 # Count of display tags on Tags Widget

  rpx_auth:
    apiKey:  858abb400e90a9fc583926b695fb4b17395f6013 # Key for RPX authetification
    domain:  'rq.rpxnow.com'
    token:   'rq.forma-dev.com/auth/RPXAuth'

#  rpx_auth: # qaweb apiKey
#    apiKey:     661785c98da222a3540dd923f5348fe7d46b58ba

  recent_users:
    to_display:   9

  offensive:
    confirmation_text:  Are you sure you want to flag this post as offensive or spam?