userSettingsSuccess:
  metas:
    robots:         noindex
    title:          Audio Recording Question and Answers Community - <?php echo sfConfig::get('app_domain_name')."\n" ?>
    description:    Find the answer to all your recording questions and earn experience and rewards in the worlds simplest online recording community.

editStudioImageSuccess:
  javascripts: ['/min/b=js&f=addNewGear.js,companyDetail.js,gearDetail.js']